export const UPDATE_SEARCH_BOX = 'UPDATE_SEARCH_BOX';
export const UPDATE_NEXT_HREF = 'UPDATE_NEXT_HREF';
export const SEARCH_FOR_ITEM = 'SEARCH_FOR_ITEM';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SHOW_PLAYER = 'SHOW_PLAYER';
export const HISTORY_PUSH = 'HISTORY_PUSH';


