export const SEARCH_FOR_ITEM = 'SEARCH_FOR_ITEM';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRAC';
export const HISTORY_PUSH = 'HISTORY_PUSH';


